GET http://127.0.0.1/router

###
POST https://empbackend-ilha.onrender.com/router/create
Content-Type: application/json

{
    "fullName": "Pranesha",
    "email": "1yy34@gmail.com",
    "contactNo": "01223456789",
    "dob":"09/12/2001",
    "department":"IT"
}